### ISSUE TITLE
Done: Unity 2022.2 and Sprite Atlas V2 bug

### ISSUE THREAD

**Issue by Gasparfx** [sr4dev/Unity-SpriteAssist#49]
Hi!
Plugin is great and very useful. But i have a bug with new Unity(2022.2). Preview window is not working correctly with Sprite Atlas V2.
Here are screenshots of the bug:
![image](https://user-images.githubusercontent.com/3947711/212613427-f3442ead-d7d4-4c1e-ac0e-a13d00546f8d.png)
![image](https://user-images.githubusercontent.com/3947711/212613551-0c64c1cd-1e11-49dd-8a0e-50971fd3fb26.png)

**Comment by sr4dev** [comment]
Thanks for letting me know. I'll take care of it.

**Comment by sr4dev** [comment]
I have been able to reproduce the bug and found additional critical bugs. As a result, it seems that it will take quite some time to support sprite Atlas V2 in Unity 2022.2.

https://github.com/sr4dev/Unity-SpriteAssist/blob/main/README.md#known-issues
I have added Known Issue on the main page for now. I recommend not to use sprite Atlas V2 if possible.
I would appreciate it if you could wait for a while until the problem is resolved.

**Comment by Gasparfx** [comment]
Thanks for letting us know. It seems like i can use option "Sprite Atlas V2 - Enabled For Builds" for now. Waiting for the fix.

**Comment by sr4dev** [comment]
I have discovered that using SpriteAtlasV1 in Unity 2022.2 may cause issues with Dynamic Batching not working(URP, Built-in both). The issue of Dynamic Batching not working when using spriteAtlasV1 in Unity 2022.2 occurs independently of SpriteAssist. It may be best to use "Sprite Atlas V2 - Enabled For Builds" instead of using SpriteAtlasV1 for the time being.

**Comment by sr4dev** [comment]
@Gasparfx  Modified it. Released a new version.
https://github.com/sr4dev/Unity-SpriteAssist/releases/tag/v1.0.6

**Comment by Gasparfx** [comment]
@sr4dev Thanks a lot!
Its much better now. I still have a problem with preview window sometimes, but it looks like a different bug and not related to Sprite Atlases. So i will make another thread.
